/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaSelect: typeof import('./src/components/AreaSelect.vue')['default']
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DestinationSelect: typeof import('./src/components/DestinationSelect.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InsuredCountInput: typeof import('./src/components/InsuredCountInput.vue')['default']
    InsuredDisplay: typeof import('./src/components/InsuredDisplay.vue')['default']
    InsuredForm: typeof import('./src/components/InsuredForm.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TravelForms: typeof import('./src/components/TravelForms.vue')['default']
    TypeInsurance: typeof import('./src/components/TypeInsurance.vue')['default']
    VCountInput: typeof import('./src/components/VCountInput.vue')['default']
    VDateInput: typeof import('./src/components/VDateInput.vue')['default']
    VGroupItems: typeof import('./src/components/VGroupItems.vue')['default']
    VSelectInput: typeof import('./src/components/VSelectInput.vue')['default']
    VText: typeof import('./src/components/VText.vue')['default']
    VTextInput: typeof import('./src/components/VTextInput.vue')['default']
  }
}
