/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaSelect: typeof import('./src/components/AreaSelect.vue')['default']
    BuilderContent: typeof import('./src/components/BuilderContent.vue')['default']
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    copy: typeof import('./src/components/VDateInput copy.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DestinationSelect: typeof import('./src/components/DestinationSelect.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImgBackground: typeof import('./src/components/ImgBackground.vue')['default']
    ImgBackGround: typeof import('./src/components/ImgBackGround.vue')['default']
    IncreaseInput: typeof import('./src/components/IncreaseInput.vue')['default']
    InsuredCountInput: typeof import('./src/components/InsuredCountInput.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TesPage: typeof import('./src/components/TesPage.vue')['default']
    TravelForms: typeof import('./src/components/TravelForms.vue')['default']
    TypeInsurance: typeof import('./src/components/TypeInsurance.vue')['default']
    VAutoComplete: typeof import('./src/components/VAutoComplete.vue')['default']
    VCountInput: typeof import('./src/components/VCountInput.vue')['default']
    VDateInput: typeof import('./src/components/VDateInput.vue')['default']
    VGroupItems: typeof import('./src/components/VGroupItems.vue')['default']
    VSelectInput: typeof import('./src/components/VSelectInput.vue')['default']
    VText: typeof import('./src/components/VText.vue')['default']
    VTextInput: typeof import('./src/components/VTextInput.vue')['default']
  }
}
